### ISSUE TITLE
Not working in IE11 on Windows 7

### ISSUE THREAD

**Issue by ericrovtar** [dollarshaveclub/stickybits#108] opened 2017-08-28 18:40 UTC
Hi!

I'm researching solutions to implement sticky behavior in older browsers and came across Stickybits; however, when I browse the demos in IE11 on Windows 7, they don't appear to actually work.

Further, I have `useStickyClasses` set to `true` and I'm only ever seeing the `js-stickybit-parent` class added.

Am I missing something?

Thanks!

**Comment by yowainwright** [comment] 2017-08-28 18:44
Stickybits should work in Internet Explorer 9 and above.

Could you submit a demo? Or use-case? ~Thanks

**Comment by ericrovtar** [comment] 2017-08-28 19:07
Apologies. It appears that there was an error on my end. I had some CSS that was interfering with it.

However, the demo still does not appear to work properly on your site in IE 11. Here's a screen recording of IE 11 on Windows 7 running on Virtual Box. This is my standard test environment, but you can see that the menu does not stick as it does in Chrome:
[Screen Recording.zip](https://github.com/dollarshaveclub/stickybits/files/1257857/Screen.Recording.zip)

**Comment by yowainwright** [comment] 2017-08-28 19:53
Please refer to a demo in the Stickybits readme. The is the landing page is probably not using the most up to date version of Stickybits.

**Comment by rosivanov** [comment] 2017-09-14 19:24
This demo https://codepen.io/yowainwright/pen/YQZPqR does not work in IE11 win7.
@yowainwright

**Comment by yowainwright** [comment] 2017-09-14 21:18
@rosivanov Thanks for sharing! I'm working on an update. I'll appreciate your feedback very soon. 🙏

**Comment by yowainwright** [comment] 2017-09-26 05:19
@here adding more tests to address issues. Hopefully by Wednesday!

**Comment by bakura10** [comment] 2017-09-26 18:18
Hi :),

I'm actually having several issues with the bottom positioning on any browser that does not support sticky natively (IE11, Edge...).

I didn't dig too much but the issue seems to come from the fact that it's positioned fixed with bottom 0, so obviously, it stays at the bottom of the screen:

<img width="1680" alt="capture d ecran 2017-09-26 a 20 17 39" src="https://user-images.githubusercontent.com/1198915/30876778-e52d8b6a-a2f7-11e7-9e48-3176d15445d0.png">

I'm not sure how you can solve that though... :p

**Comment by bakura10** [comment] 2017-09-26 18:21
Actually, your demo is fialing as well on Edge :( : https://codepen.io/yowainwright/pen/QdePbr

**Comment by yowainwright** [comment] 2017-09-26 18:22
Thanks for the detail @bakura10 ! 

The release that is coming—today/tomorrow will provide a much more usable API for the use-cases that I've learned from the help of Stickybits customers (like you).

**Comment by bakura10** [comment] 2017-09-26 18:23
Awesome. Glad to hear that. I've been using Stickyfill polyfill for ages but it didn't support bottom sticky, so I'm glad to switch to yours :p.

**Comment by yowainwright** [comment] 2017-09-28 05:08
@bakura10 I haven't `published` `v2` to npm but I tested in IE on a virtual box and it looked.

**Comment by bakura10** [comment] 2017-09-28 09:06
Hey,

I'm sorry but it completely broke on IE11 nor Edge haha (didn't try older version of IE yet). Bottom, top... nothing works :p. I can see that no classes at all are added. Are your demos updated to the new code as well? Does it require new additional required attributes?

PS: I think I may suggest as well (sorry it's unrelated) is an easier way to remove an existing instance. Currently you only have the opportunity to remove everything, but if you have several instances into the page that will make it hard.

Ideally, a syntax like this would be awesome:

```js
Stickybits.destroy(element);
```

**Comment by yowainwright** [comment] 2017-09-28 14:43
No worries—I apologize. 

It is strange because I checked IE, and it worked fine for me. I haven’t updated the examples or anything b/c I wanted to reach out to people that have filed issues first. 

https://codepen.io/yowainwright/pen/c545e49133acf2d000f4bf8b1e7fa72a

^ That is my first updated pen. I tested it in ie and everything looked fine ...?

What does that codepen demo look like for you?

I also added WAY more tests and all of those pass.

I’m hopefully this is a minor copy/paste or transpiration issue. 😃

**Comment by bakura10** [comment] 2017-09-28 15:55
No worry :p. I can't share the code for now but I'll try to reproduce a minimal use case. In the meantime, it appears that the issue is that Stickybits only adds the "top: 0" without the "position: fixed":

<img width="1159" alt="capture d ecran 2017-09-28 a 17 54 26" src="https://user-images.githubusercontent.com/1198915/30976858-3369e286-a476-11e7-833e-c24ead9431dd.png">

**Comment by yowainwright** [comment] 2017-09-28 16:14
Cool, that should be a minor fix. I’ll look at it shortly. 

Thanks for checking!!!

If there needs to be a change. I will add a PR and direct you towards it.

**Comment by yowainwright** [comment] 2017-09-28 16:58
@bakura10 I'm not seeing that issue in the codepen I shared. 

https://codepen.io/yowainwright/pen/c545e49133acf2d000f4bf8b1e7fa72a

I'm asking our qa team to look as well. 

----

**Note:** I have not published to npm yes.
In your console, get the version on your stickbits. 

```javascript

var stickybit = stickBits('el'); 
stickybit.version;

```
Ensure that the version is `2.X`. If `version` is not defined, then the version is not `2.0.0`.

**Comment by bakura10** [comment] 2017-09-28 17:01
I'm indeed using this version. If you give me your email I can try to send you access to the page.

**Comment by yowainwright** [comment] 2017-09-28 17:06
yowainwright@gmail.com

**Comment by yowainwright** [comment] 2017-09-28 17:07
@bakura10 the general functionality should be the same but v2 exposes a lot more of the API for better debugging, etc.

**Comment by yowainwright** [comment] 2017-09-28 17:33
@bakura10 okay, great news—better than even your question!

---

1. The issue in the example you shared is that Stickybits selected html element is **not** the first child of the parent. I will share more in an email to you directly. 
2. You don't need any JS based on your example! If the `nav` is always at the top and only a `child` of the `<body>` you can use `position fixed` w/o any JavaScript! You'll just need to account for the offset in `nav`'s `decendant sibling` with CSS.
3. If there something above the `nav` sometimes (like a banner), all of that can be wrapped in an `html element` and then accounted for with that element's `decendant sibling` with CSS!
 
---

In regards to how I reached this conclusion, you helped me out greatly! The comments above pointed out that I need to write better documentation on Stickybits regarding `position: sticky`! 🙏

**Comment by bakura10** [comment] 2017-09-28 17:35
Awesome. Thanks a lot for your debugging!

Indeed, this one may be solved by using position fixed and offseting. The issue is that the height is not known (those are generic themes and we can't do any assumptions on elements size).

However there is another usage of the sticky (both top and bottom) inside the page, I'll share it with you by email.

**Comment by rosivanov** [comment] 2017-09-28 18:05
Confirm, this pen https://codepen.io/yowainwright/pen/c545e49133acf2d000f4bf8b1e7fa72a works fine in IE11
@yowainwright Brilliant support, thank you! :blush:

**Comment by yowainwright** [comment] 2017-09-29 22:20
Follow up with new issues/notes on the wiki or in issues! 🙏

**Closed by yowainwright** 2017-09-29 22:20 UTC
Labels: bug
