### ISSUE TITLE
Sticky Classes aren't toggling properly if scrolltop not 0 on anchor load.

### ISSUE THREAD

**Issue by Jakob-Maudience** [dollarshaveclub/stickybits#100] opened 2017-08-14 15:01 UTC
I'm using this library in part due to the sticky class toggling (as well as for the polyfill). Although I've ran into some issues for when the class is added or removed.

If the scroll position is not at 0 on pageload, the sticky classes don't get added properly. for instance, if the page loads on an anchor (id hash), the script thinks that's where the page head is. ( you scroll up and the stickyclass is added, but you scroll down to that anchor point, and the stickyclass is removed).
Likewise, if you scroll down a little ways, and reload (without a url hash), the stickyclass is always present, and never removed.

Here's my bin, blue header background is not sticky, purple background is sticky.
[http://jsbin.com/rejuramuku/1/edit?html,css,console,output](url) 

You will have to view the bin without the editor in order to refresh with an anchor hash url. [http://jsbin.com/rejuramuku/](url)

**Comment by Jakob-Maudience** [comment] 2017-08-14 15:03
It seems that this issue was already posted. Sorry about that. Feel free to delete.

**Comment by kvanberendonck** [comment] 2017-08-14 20:27
Thank you for being able to reproduce in isolated test case, I was not able to reproduce in plunkr

**Comment by yowainwright** [comment] 2017-08-14 20:38
I will try to address some of the issues in Stickybits ASAP. 

Thanks for the note @Jakob-Maudience!

**Comment by yowainwright** [comment] 2017-09-26 05:20
@here adding more tests to address issues. Hopefully by Wednesday!

**Comment by sissel-siv** [comment] 2017-09-26 20:32
My quickfix solution for this that works my end.

```
var acquire = (function () {

    var fn = {};

    fn.addEvent = function(object, type, callback) {
        if (object == null || typeof(object) == 'undefined') return;
        if (object.addEventListener) {
            object.addEventListener(type, callback, false);
        } else if (object.attachEvent) {
            object.attachEvent("on" + type, callback);
        } else {
            object["on"+type] = callback;
        }
    };

    fn.offset = function(evt) {
        var scroll = evt.target.body.scrollTop;
        return scroll;
    };
    return fn;

})();

```

From here, just init as follows:

```
acquire.addEvent(window, 'scroll', function(event){
   if (acquire.offset(event) <= 0) {
       stickybits('#sticky-element').cleanup();
   } else {
        stickybits('#sticky-element', {
            stickyBitStickyOffset: -1,
            useStickyClasses: true
        });
    }
}, true);

```

Hope this helps!

**Comment by yowainwright** [comment] 2017-10-05 07:01
@panoply Thank you! I'll review what you've done ASAP. 🙏

**Comment by stanza237** [comment] 2017-12-20 11:38
I think that my problem is related to this thread: when opening page with an anchor (not at top 0) sticky class is not applied (earlier version 2.0.13 was applying it). Then when page is scrolled the class is applied, but then when page is at "top 0" it isn't removed, that is what i need

**Comment by ajithbhat** [comment] 2018-01-04 15:57
I had the same issue. To resolve this I had to create a function to calculate offsetTop

`var getOffsetTop = function getOffsetTop(elem) {
  var offsetTop = 0;
  do {
    if (!isNaN(elem.offsetTop)) {
      offsetTop += elem.offsetTop;
    }
  } while (elem = elem.offsetParent);
  return offsetTop;
};` 

And use the above method in computeScrollOffsets function:

Stickybits.prototype.computeScrollOffsets = function computeScrollOffsets(item) {
  var it = item;
  var p = it.props;
  var parent = it.parent;
  var iw = it.isWin;
  var scrollElOffset = 0;
//  let stickyStart = parent.getBoundingClientRect().top
  var stickyStart = getOffsetTop(parent); 
  if (!iw && p.positionVal === 'fixed') {
//    scrollElOffset = p.scrollEl.getBoundingClientRect().top
    scrollElOffset = getOffsetTop(p.scrollEl); 

//    stickyStart = parent.getBoundingClientRect().top - scrollElOffset
    stickyStart = stickyStart - scrollElOffset;
  }
  it.offset = scrollElOffset + p.stickyBitStickyOffset;
  it.stickyStart = stickyStart - it.offset;
  it.stickyStop = stickyStart + parent.offsetHeight - (it.el.offsetHeight + it.offset);
  return it;
};

A new release with these changes would be helpful.
TIA
Ajith

**Comment by dackmin** [comment] 2018-01-27 21:48
@yowainwright I'm also having the issue with `2.0.13`, only by refreshing a normal page at a non-zero scroll position, and I can replicate it using the `useStickyClasses` example provided in the `README` (https://codepen.io/yowainwright/pen/NpzPGR).

If you scroll enough only to have `child` items in viewport, they will correctly have a `js-is-stuck` class applied : 

<img width="970" src="https://user-images.githubusercontent.com/1873323/35476610-2b080a36-03b3-11e8-85d3-07d5face2dce.png">

But if you right click into the `run` frame of codepen and click on `refresh frame` (using chrome, I don't know if any other browser has this option), the frame will be refreshed at the current scroll position, and the element won't have any `js-is-*` class applied : 

<img width="967" src="https://user-images.githubusercontent.com/1873323/35476651-a45df490-03b3-11e8-8c36-dfd83da64336.png">

Again, if you scroll back to the position where the element is supposed to change from `js-is-stuck` to `js-is-sticky` (or the opposite), the new class is applied correctly.

**Comment by DanielRuf** [comment] 2018-02-10 11:52
It is because the initial calculation starts directly and just works when we start from the top. Scrolling and loading takes a while the autoatic scrolling is happening.

**Comment by DanielRuf** [comment] 2018-02-10 11:54
Same for websites where we do not use an anchor but a scroll position (simple F5 reload). We may have to investigate this further and write some unit tests to catch this.

**Comment by yowainwright** [comment] 2018-02-13 05:02
@DanielRuf I think events can be used to support _some_ of this issue.

**Comment by steveooo9** [comment] 2018-03-17 01:35
@yowainwright Yeah, I think is is something that should be fixed because it's somewhat a bug. A lot of people do a F5 refresh (or CMD+R) and when they scroll to something, the browser tries to keep at this scroll position after reload. I don't know the real logic browser specifics behind all this, but even so it's something that should be "normalized" or fixed to work with all ways.

**Comment by DanielRuf** [comment] 2018-03-17 11:24
Might to do with the state (document.readystate).

**Comment by steveooo9** [comment] 2018-03-17 19:20
Maybe this? https://stackoverflow.com/questions/15355839/how-to-let-the-chrome-forget-the-page-scroll-position

**Comment by yowainwright** [comment] 2018-03-17 21:08
@DanielRuf @steveooo9 Hey! 🙂 

I don't think that the Stickybits feature/update that we'll make (soon btw 🎸) should support various things that "might" happen to change a Stickbits instance's state. I think Stickybits should provide a way that the implementer can control when their implementation of Stickybits needs an adjustment its state. The reason that I think this is that the issue described can happen in not just _doc ready_ or a _url change_. It could happen with a  _window resize_ and many more things. 

...So, if Stickybits can provide a hook to update/change a Stickybits instance's state based an event (probably an event) or method than that can provide a way for the implementer to manage when a Stickybits instance's state needs to be updated and not just us guessing when might be a good time to update a Stickybits instance's state.

**Comment by steveooo9** [comment] 2018-03-18 00:40
@yowainwright Yeah, I partially agree with that.
But it still should work and mostly be bug-free.

Currently when on the Stickybits website and you scroll some time and reload, the "is Stuck! 🔥" is buggy. So this is something that should be addressed (I think).

So maybe Stickybits catches all this changes and gives a public `update()` method. Maybe this is enough, so we could say when to trigger update to make stickybits work in the new environment (new scroll position, etc.)).

But why not include some simple event listener that catches window resizes, scroll and reloads?

**Comment by yowainwright** [comment] 2018-03-18 07:49
@steveooo9 if you have a fix for this issue, please submit a pull request. If there is an issue with the landing page, please file an issue and technically document what is wrong with browser, logs, gifs, OS, etc.

**Comment by steveooo9** [comment] 2018-03-19 20:17
@yowainwright No, I didn't fix this. I upload a video of the buggy behavior which probably is the same bug as in this task.
![bug](https://user-images.githubusercontent.com/27959355/37619814-d6a927d8-2bba-11e8-923c-eee939c38a95.gif)

**Comment by panoply** [comment] 2018-03-20 03:36
Can someone post this issue on [flems](https://flems.io/) – I cannot seem to recreate it in my environment locally. I had this issue in the past and managed to fix it.

**Comment by yowainwright** [comment] 2018-03-20 03:38
@panoply I'll be working on the actual issue soon—hopefully. If someone can post the on flems, though—that **would** be cool.

**Comment by Daidalos117** [comment] 2018-04-29 12:30
Any progress? It's really annoying :/

**Comment by yowainwright** [comment] 2018-04-29 13:37
@Daidalos117 the sentence, ”It’s really annoying” is inappropriate because it is negative in context and doesn’t help the Stickbits community.

There is nothing stopping you for digging into the code and seeing that a fix has been added—which it seems you did not do.

**Comment by yowainwright** [comment] 2018-06-14 20:56
#295 will be wrapped up shortly (next few days). Sorry about the wait.

**Closed** 2018-06-19 21:44 UTC
Labels: documentation, enhancement
