### ISSUE TITLE
Do you know why it sticks up so soon on ie 11? 

### ISSUE THREAD

**Issue by etiennejcharles** [dollarshaveclub/stickybits#184] opened 2017-12-22 21:44 UTC
Hey there! Thank you guys for such an amazing polyfill! 

I was curious to know, if you had an idea why it sticks up the moment I scroll on the page **on ie 11**, I expected it to wait until I arrived on the element!

http://138.197.158.15/history

Please let me me know if you have an idea! There's probably something I missed. 
I simply used the plugin like so : 

```js
stickybits('.slider-section', { useStickyClasses: true });
```

Thank you again the the amazing work you guys are doing!

**Comment by yowainwright** [comment] 2017-12-24 05:35
@etiennejcharles I'll look asap! It might not be an issue on the website you shared's end. 😊

There were some updated [here](https://github.com/dollarshaveclub/stickybits/issues/160) that may need some tweaking in a slightly different way. 

Thanks for letting me know!

**Comment by yowainwright** [comment] 2018-01-16 07:02
@etiennejcharles sorry for the delay! 

The issue is that the stickybit needs to be wrapped in a parent element besides the document. Because the stickybit is not in a parent element when it is set to `postion: fixed` (AKA, in internet explorer) it looks for a parent which is the document. 

Try something similar to this:

```html
<body>
<div>
</div>
<div id="sticky-parent">
  <div id="stickybit"></div>
</div>
</body>
```

**Comment by yowainwright** [comment] 2018-01-20 22:41
@etiennejcharles closing this. Reach out if I can help with anything else. 👋

**Closed by yowainwright** 2018-01-20 22:41 UTC
