### ISSUE TITLE
Update properties without creating new instance

### ISSUE THREAD

**Issue by nthibert** [dollarshaveclub/stickybits#296] opened 2018-05-04 15:55 UTC
Is there a way to update the properties and refresh the current instance of stickybits without the need to create a whole new instance. I have looked at update, but seems it's not updating my offset.

**Comment by yowainwright** [comment] 2018-05-04 23:55
@nthibert hmm, what offset are you talking about specifically?

**Comment by yowainwright** [comment] 2018-05-05 00:29
@nthibert that's a great point, `.update()` only updates the StickyBits sticky calculations and not `stickybitsStickyOffset`. 

...but I think you can update the `stickybitsStickyOffset` of each Stickybits instance in the `instances` array. It might look something like this:
```javascript
// **NOTE:** this is off the top of my head so it by be slightly off
const stickybit = Stickybits('thing', {stickybitsStickyOffset: 5})
stickybit.instances[0].props.stickybitsStickyOffset = 10
```
Sorry if I'm totally off base. I'm trying to provide feedback quickly.

**Comment by nthibert** [comment] 2018-05-05 01:10
Would this actually update the element style. I believe the offset gets set to the top property. So just updating the prop might not be enough. Maybe manageState might need to be called? 

Possible future function maybe an update with params passed in to update the initial config and re-render on the element.

**Comment by yowainwright** [comment] 2018-05-05 22:53
@nthibert you're right about the element not getting updated. `.manageState` wouldn't help. You could update both—or not have Stickybits manage the offset of the sticky element (just quick ideas). 

In regards to the future feature: update with params passed in to update the initial config and re-render on the element—that is a thoughtful idea! Initially, I feel like it would be too much but I'm going to think about it for a bit.

**Comment by yowainwright** [comment] 2018-05-10 21:11
The wontfix tag was added to signify:
- this is not a bug
- it is a thoughtful feature idea
- a similar feature may be at a later date (but is not actively being considered)

**Comment by yowainwright** [comment] 2018-06-14 20:55
Provide a thumbs up here if you want this feature. If there are enough thumbs up, this feature will be added.

**Closed by yowainwright** 2018-06-14 20:55 UTC
Labels: feature, wontfix
