### ISSUE TITLE
Set width of sticky element if `position: fixed`

### ISSUE THREAD

**Issue by BMCwebdev** [dollarshaveclub/stickybits#80] opened 2017-07-26 21:59 UTC
Am I correct in understanding that in IE, as css sticky is not supported, this will add a position:fixed? I ask because I am dealing with a div inside a flexbox item. If I position fixed it, it looses it's parents width and no longer behaves as if it is contained in the parent. Thank you (sorry, not sure how to add the "question" label.)

**Comment by yowainwright** [comment] 2017-07-27 17:59
I'm going to write an update for this particular feature as it has been requested a lot. I will try to have is ASAP.

**Comment by yowainwright** [comment] 2017-07-28 05:17
@BMCwebdev here's another [issue](https://github.com/dollarshaveclub/stickybits/issues/66) referencing this same general thing. There are a lot of different ways to fix the valid problem you noted. 

Stickybits won't support adding `width` for sticky elements b/c there are many scenarios where that wouldn't be the desired option (think of a sticky element that doesn't extend the full width of the parent). Let me know if I can help come up with the right solution. 

Thanks for reaching out! 🙏

**Comment by yowainwright** [comment] 2017-07-28 05:21
Duplicate of #66

**Comment by kvanberendonck** [comment] 2017-07-28 05:21
+1 this, behaviour is inconsistent under IE otherwise

**Closed by yowainwright** 2017-07-28 05:21 UTC
Labels: question
