### ISSUE TITLE
js-is-sticky selector gets added late

### ISSUE THREAD

**Issue by nthibert** [dollarshaveclub/stickybits#302] opened 2018-05-16 17:59 UTC
Hey, I ran into an issue or designed feature. So when I have an element that is underneath a already sticky element and I add an offset to it to support not going over the first element. Seems like js-is-sticky is only being applied when the parent element has scrolled passed the top viewport and not when the element gets actually stuck. Not sure if this is working as expected or if it's an actual bug. You can see this on https://dollarshaveclub.github.io/stickybits/ where the stuck with the fire beside it gets added later than when the element actually gets stick.

**Comment by yowainwright** [comment] 2018-05-16 18:02
1. The landing page uses an old version of Stickybits. Someone should update it. 
2. That is by design—but should be fixed. Do you want to do it @nthibert?

**Comment by nthibert** [comment] 2018-05-16 18:14
I can look into it, just wanted to make sure what the logic was before actually modifying the code

**Comment by yowainwright** [comment] 2018-05-16 19:17
@nthibert thanks and thanks for checking in.

**Comment by yowainwright** [comment] 2018-06-19 21:15
@nthibert this is the line that may need to be updated:

- https://github.com/dollarshaveclub/stickybits/blob/master/src/stickybits.js#L222

Happy to review a PR if the line is incorrect.

**Closed by yowainwright** 2018-06-19 21:15 UTC
Labels: bug
