### ISSUE TITLE
js-is-sticky is applied when sibling reaches top of page, not when sticky element actually sticks

### ISSUE THREAD

**Issue by w-biggs** [dollarshaveclub/stickybits#223] opened 2018-02-04 00:16 UTC
I've thrown some of my code into a codepen (sorry if it's a little messy):
https://codepen.io/anon/pen/eVZZEZ

What's happening is that `.headnav` gets applied with the `.js-is-sticky` class as soon as its sibling, `header`, reaches the top of the viewport. The intended result is that the class is applied when `.headnav` itself reaches the top of the viewport and is sticking.

Any clue why this happens? Thanks.

**Comment by DanielRuf** [comment] 2018-02-04 00:18
Used version: 3.0.1

**Comment by yowainwright** [comment] 2018-02-05 18:25
@w-biggs did @DanielRuf's not help? 😊

**Comment by DanielRuf** [comment] 2018-02-05 20:23
> @w-biggs did @DanielRuf's not help? 😊

I just added the information about which version the issue reporter uses so we can better track this. I thought we have an issue template but it seems we have none (might make debugging easier).

**Comment by w-biggs** [comment] 2018-02-05 21:26
Yeah, I'm using 3.0.1 already - sorry for not specifying.

**Comment by yowainwright** [comment] 2018-02-08 18:24
@w-biggs @DanielRuf  I'm not saying that there is not a bug here but there is an issue with the setup in the codepen. Please review [this](https://developer.mozilla.org/en-US/docs/Web/CSS/position)—mainly `position: sticky`. 

Sorry I won't be able to help here more for the next week/2 weeks. 

~Thanks

**Comment by w-biggs** [comment] 2018-02-09 20:01
@yowainwright I see no issue with how the codepen is set up based on the specification found there - what am I missing?

**Comment by yowainwright** [comment] 2018-02-09 20:05
@w-biggs here you go. Sorry for the copy/paste job. This is right from this same [link](https://developer.mozilla.org/en-US/docs/Web/CSS/position) again. 😊 . 

![position_-_css___mdn](https://user-images.githubusercontent.com/1074042/36047534-473c405e-0d91-11e8-9483-8189a63bcf07.jpg)

"containing block" is the key word. That is a confusing but important difference between `position: fixed` and `position: sticky`.

**Comment by w-biggs** [comment] 2018-02-09 20:12
Ah okay, thanks. The spec is confusing - further down the page, it says that it switches when the element itself reaches the threshold (which is the behavior I'm seeing in-browser, but not by this plugin). I wonder if every browser is misinterpreting the spec in this case? Hm.

**Comment by yowainwright** [comment] 2018-02-09 20:20
@w-biggs thanks for your thoughts! 

This issue has traversed to a non-stickybits issue so I'm closing it. 😊

----

For further demos check out other closed issues or [this page from the Stickybits wiki](https://github.com/dollarshaveclub/stickybits/wiki/Understanding-Stickybits-and-Position-Sticky).

**Closed by yowainwright** 2018-02-09 20:20 UTC
